version = 0.1

[default.deploy.parameters]
stack_name = "hamo-backend"
resolve_s3 = true
s3_prefix = "hamo-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"HamoPro\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
